### ISSUE TITLE
Could not load map! 

### ISSUE THREAD

**Issue by VoteNix0n** [Caballero-Arepa/Community-Maps#5]
Am getting errors when loading the custom maps, either "Could not load map!" or "Invalid Map: Area (4959) does not match saved dimensions (44x29).". Are you aware of any fix?

**Comment by Caballero-Arepa** [comment]
Hi, I'm sorry for this but currently this are the problems:
1. I need either to re-do the map or ask some to fix the format
2. I have currently 'retired' from Unciv stuff as I am very busy sorting life and so I dont have time to fix. I have the hopes to someday come back and fix everything.
